// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://cnxfbkapywwomewhxwhr.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImNueGZia2FweXd3b21ld2h4d2hyIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjM2MjgzNzAsImV4cCI6MjA3OTIwNDM3MH0.HGy1DgDlHi2XyM5GySKQ5P4zlbgahC2sKXeV6_Ir-To";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});